package main

// createInitialStoryMissions returns the default set of story missions for a new user
func createEmptyStoryMissions(today string) []StoryMission {
	return []StoryMission{
		{
			StoryId:      "story_1",
			Criteria:     "Start the Game",
			Title:        "A Smashing Debut",
			DateAchieved: today,
			PlayerName:   "",
		},
		{
			StoryId:      "story_2",
			Criteria:     "Start a Case",
			Title:        "A Smashing Debut",
			DateAchieved: today,
			PlayerName:   "",
		},
		{
			StoryId:      "story_3",
			Criteria:     "Solve 1 Case",
			Title:        "A Smashing Debut",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_4",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_5",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_6",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_7",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_8",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_9",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_10",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_11",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_12",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_13",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_14",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_15",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_16",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_17",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_18",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_19",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_20",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_21",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_22",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_23",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_24",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_25",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_26",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_27",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
		{
			StoryId:      "story_28",
			Criteria:     "",
			Title:        "",
			DateAchieved: "",
			PlayerName:   "",
		},
	}
}
